//! Static pipeline DSL — the `#[pipeline]` and `#[stage]` attribute macros.
//!
//! Runtime support types (`Value`, `Vector`, `Buckets`, `Reset`, `Error`) live
//! in the `pipeline` crate ([`pipeline-core`]); depend on it directly and refer
//! to them as `pipeline::Vector`, `pipeline::Reset`, etc. Code generated by
//! `#[pipeline]` references those `pipeline::…` paths, so a crate using the
//! macro must have `pipeline-core` as a direct dependency.
//!
//! [`pipeline-core`]: https://crates.io/crates/pipeline-core
pub use pipeline_macros::{pipeline, stage};
